services:
  - type: web
    name: fitzo-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FATSECRET_CLIENT_ID
        sync: false
      - key: FATSECRET_CLIENT_SECRET
        sync: false
      - key: USDA_API_KEY
        sync: false
